# Generated by Django 4.2.6 on 2023-11-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cars", "0009_alter_orderquantity_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="blocked_by_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_cars",
                to="Cars.order",
            ),
        ),
    ]
