# Generated by Django 4.2.6 on 2023-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cars", "0010_car_blocked_by_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartype",
            name="image",
            field=models.ImageField(blank=True, upload_to="arn:aws:s3:::hillel-carstore"),
        ),
    ]
