# Generated by Django 4.2.9 on 2024-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cars", "0011_cartype_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=100, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="image",
        ),
    ]
