# Generated by Django 4.2.9 on 2024-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cars", "0013_alter_car_owner_alter_order_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartype",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="arn:aws:s3:::hillel-carstore"
            ),
        ),
    ]
